### ISSUE TITLE
What do you mean, blocked from the org?  :(

### ISSUE THREAD

**Issue by MiracleBlue** [Cutlery-Drawer/language-html#1]
Love your work buddy, not sure why anyone would dislike your contributions let alone block you from a repo.  Just wanted to give you some positivity :)

**Comment by Alhadis** [comment]
I'm pretty baffled. 😕 I, erh, resorted to spamming one of @50Wliu's own repositories just to ask...

https://github.com/50Wliu/language-ibcm/commit/9c6e4a2e92e8f5ad69b39790769199e3ef726fb2

Since I was utterly unable to comment on *any* repository hosted by the @atom org, for reasons yet to be disclosed...

**Comment by Alhadis** [comment]
Also, if this *is* a deliberate block on their part, then the Atom team are warned I'm the most notoriously stubborn bastard on the planet, and blocking me will just make me find ways of *indirectly* contributing to their project. To a fault of being annoying, depending on the importance of the submission.

I'm like a pitbull that submits patches instead of rip people's legs off...

(I'm tempted to chalk all this up as a giant glitch or something, because blocking me wouldn't even make sense...)

**Comment by MiracleBlue** [comment]
Yeah I bet it's some sort of super weird glitch or even an accidental status change or something. I couldn't even imagine why you of all people would end up blocked on any repo. Anyway I hope it gets resolved soon!!

**Comment by Alhadis** [comment]
I don't know why I always forget about communication mediums that *aren't* GitHub-related.

Just sent an e-mail to atom@github.com:

> Hello,
> 
> It recently came to my attention that I may have been blocked from the @atom org at GitHub (my username is @Alhadis). I'm unable to comment on any Atom-related repository, submit issues or pull-requests, or even star anything (as I noticed several repos missing from my "Starred" list).
> 
> If this is was a deliberate banning, then I request at least a notification, never mind a decent explanation.
> 
> I can't fathom why you'd ban a frequent contributor, so I suspect this may be some glitch or mishap. Nonetheless, I'd appreciate some insight.
> 
> Thank you,
> \- John (Alhadis @ GitHub)

Which really should've been the first thing I did...

**Comment by MiracleBlue** [comment]
Did they reply?  I hope it was all just an accident :) I'm sure it was.

**Comment by MiracleBlue** [comment]
Btw, I noticed that your username still has the "contributor" badge next to it on the Atom repos

**Comment by Alhadis** [comment]
You're so sweet it makes me sick. ❤️

And yeah, but at least @github [still love me](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#maintainers). 😂 I hope.

**Comment by Alhadis** [comment]
So it was on purpose.

Their loss. Not mine.
